### PR TITLE
Fixes for #36, #35, #32 + download all feature, and backend refactor w/ dedup

### LINKED ISSUE #32: Add Confirmation Message / Progress Bar for Uploads
We need to add a confirmation message or some visual way for users to know that the pictures they are uploading have uploaded successfully.

### LINKED ISSUE #35: Fix zone logic for deploy role
When updating the deploy_map zone it doesn't pick up the change and adjust the
iam deploy permissions.

Change SSM parameter setup for the zone id variable

### LINKED ISSUE #36: Set log group expire times to something reasonable

### PR DESCRIPTION
**Pull request by shollingsworth**
Worked on this this weekend, and tested some deploy stuff late this after noon.

Only IAM perm change was to layers, but deploy job should take care of it.

Before we merge, we should delete the existing backend stack.

Here's a a demo of what the site looks like live. (will tear it down once it's up in code4sac)

https://hostbeat.link/

### CODE REVIEW

File: frontend/src/plugins/global_mixin.js [hunk 1]
```diff
@@ -33,13 +51,219 @@ var GlobalMixin = {
...
             }
             return this.$refs[ref_id]
         },
+        async doremove(sub) {
+            console.log("remove", sub)
+            await this.$store.dispatch("images/remove", sub.hash)
+        },
+        async doupload(files) {
+            ;[...files].forEach(async (file) => {
+                const reader = new FileReader()
```
Comment (shollingsworth) [inline frontend/src/plugins/global_mixin.js:92]: note for myself, there is a function I made for this that has some error handling.

File: frontend/src/store/images.js [hunk 2]
```diff
@@ -0,0 +1,123 @@
...
+})
+
+export const mutations = {
+    clear(state) {
+        state._uploads = []
+        state._inprogress = []
+        db.trash.clear()
+    },
+    setModelState(state, val) {
+        // offline
```
Comment (shollingsworth) [inline frontend/src/store/images.js]: this is now boolean, get rid of these comments.

**Review by feydan — APPROVED** [review]
